default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  adapter:  postgresql
  port:     <%= Rails.application.secrets.database_port %>
  host:     <%= Rails.application.secrets.database_host %>
  database: <%= Rails.application.secrets.database_database %>
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>

test:
  <<: *default
  host:     localhost
  database: idoimaging_test

production:
  <<: *default
  adapter:  postgresql
  encoding: utf8
  port:     <%= Rails.application.secrets.database_port %>
  host:     <%= Rails.application.secrets.database_host %>
  database: <%= Rails.application.secrets.database_database %>
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
